services:
  webserver:
    image: luxalpa_com:latest
    restart: always
    environment:
      USE_PROD_TLS: 1
    ports:
      - "80:3000"
      - "443:443"
    volumes:
      - card-cache:/app/cache
      - acme-cache:/app/acme
    depends_on:
      db:
        condition: service_healthy

  webserver-dev:
    image: luxalpa_com:latest
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      USE_PROD_TLS: 0
    profiles: [ dev ]
    secrets:
      - postgres_password
    volumes:
      - acme-cache:/app/acme

volumes:
  acme-cache:
