services:
  webserver:
    image: luxalpa_com:latest
    restart: always
    environment:
      USE_PROD_TLS: 1
    ports:
      - "80:3000"
      - "443:443"
    volumes:
      - acme-cache:/app/acme
      - ./content:/app/content

  webserver-dev:
    image: luxalpa_com:latest
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      USE_PROD_TLS: 0
    profiles: [ dev ]
    volumes:
      - acme-cache:/app/acme
      - ./content:/app/content

volumes:
  acme-cache:
